config/routes.rb
Rails.application.routes.draw do
  concern :paginatable do
    get '(page/:page)', action: :index, on: :collection, as: ''
  end
  resources :movies, concerns: :paginatable
  get 'home/index'
  get 'home/about', as: 'about'
  root to: 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]

  # GET /movies
  # GET /movies.json
  def index
    @movies_count = Movie.count
    @random_page = params[:page] || 1
    @movies = Movie.order(:id).page @random_page
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:title, :description, :movie_length, :release_date, :rating)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.erb
<article class="message is-primary">
  <div class="message-header">
    <p>Primary</p>
    <button class="delete" aria-label="delete"></button>
  </div>
  <div class="message-body">
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. <strong>Pellentesque risus mi</strong>, tempus quis placerat ut, porta nec nulla. Vestibulum rhoncus ac ex sit amet fringilla. Nullam gravida purus diam, et dictum <a>felis venenatis</a> efficitur. Aenean ac <em>eleifend lacus</em>, in mollis lectus. Donec sodales, arcu et sollicitudin porttitor, tortor urna tempor ligula, id porttitor mi magna a neque. Donec dui urna, vehicula et sem eget, facilisis sodales sem.
  </div>
</article>

app/views/home/index.html.erb
<div class="content is-medium">
  <h1>Hello World</h1>
  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla accumsan, metus ultrices eleifend gravida, nulla nunc varius lectus, nec rutrum justo nibh eu lectus. Ut vulputate semper dui. Fusce erat odio, sollicitudin vel erat vel, interdum mattis neque.</p>
  <h2>Second level</h2>
  <p>Curabitur accumsan turpis pharetra <strong>augue tincidunt</strong> blandit. Quisque condimentum maximus mi, sit amet commodo arcu rutrum id. Proin pretium urna vel cursus venenatis. Suspendisse potenti. Etiam mattis sem rhoncus lacus dapibus facilisis. Donec at dignissim dui. Ut et neque nisl.</p>
  <ul>
    <li>In fermentum leo eu lectus mollis, quis dictum mi aliquet.</li>
    <li>Morbi eu nulla lobortis, lobortis est in, fringilla felis.</li>
    <li>Aliquam nec felis in sapien venenatis viverra fermentum nec lectus.</li>
    <li>Ut non enim metus.</li>
  </ul>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="content has-text-centered">
    <p>
      <strong>Bulma</strong> by <a href="https://jgthms.com">Jeremy Thomas</a>. The source code is licensed
      <a href="http://opensource.org/licenses/mit-license.php">MIT</a>. The website content
      is licensed <a href="http://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY NC SA 4.0</a>.
    </p>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar is-fixed-top" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <%= link_to root_url, class: 'navbar-item' do %>
      <img src="https://bulma.io/images/bulma-logo.png" width="112" height="28">
    <% end %>

    <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      <%= link_to root_url, class: 'navbar-item' do %>
        <span>Home</span>
      <% end %>

      <%= link_to movies_url, class: 'navbar-item' do %>
        <span>Movies</span>
      <% end %>

      <%= link_to about_url, class: 'navbar-item' do %>
        <span>About</span>
      <% end %>
    </div>

    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
          <a class="button is-primary">
            <strong>Sign up</strong>
          </a>
          <a class="button is-light">
            Log in
          </a>
        </div>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bulma Movies Rails</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="has-navbar-fixed-top" data-controller="main">
    <%= render 'layouts/navbar' %>
    <section class="section">
      <div class="container" style="min-height: 65vh">
        <%= yield %>
      </div>
    </section>
    <%= render 'layouts/footer' %>
  </body>
  <script>
    document.addEventListener('DOMContentLoaded', () => {

      // Get all "navbar-burger" elements
      const $navbarBurgers = Array.prototype.slice.call(document.querySelectorAll('.navbar-burger'), 0);

      // Check if there are any navbar burgers
      if ($navbarBurgers.length > 0) {

        // Add a click event on each of them
        $navbarBurgers.forEach( el => {
          el.addEventListener('click', () => {

            // Get the target from the "data-target" attribute
            const target = el.dataset.target;
            const $target = document.getElementById(target);

            // Toggle the "is-active" class on both the "navbar-burger" and the "navbar-menu"
            el.classList.toggle('is-active');
            $target.classList.toggle('is-active');

          });
        });
      }

    });
  </script>
</html>

app/views/movies/_form.html.erb
<%= form_with(model: movie, local: true) do |form| %>
  <% if movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title, :class => "label" %>
    <%= form.text_field :title, :class => "input", :placeholder => "Great title" %>
  </div>

  <div class="field">
    <%= form.label :description, :class => "label" %>
    <%= form.text_area :description, :class => "input", :placeholder => "Great description", style: 'height: 40vh;' %>
  </div>

  <div class="field is-grouped is-grouped-centered">
    <div class="field">
      <%= form.label :movie_length, :class => "label"  %>
      <%= form.text_field :movie_length, :class => "input", :placeholder => "1h26 for example" %>
    </div>
    <div class="field">
      <%= form.label :release_date, :class => "label"  %>
      <%= form.text_field :release_date, :class => "input", :placeholder => "Great release date" %>
    </div>
    <div class="field">
      <%= form.label :rating, :class => "label"  %>
      <%= form.text_field :rating, :class => "input", :placeholder => "How many stars?" %>
    </div>
  </div>

  <div class="field is-grouped is-grouped-centered">
    <p class="control actions">
        <%= form.submit :class => 'button is-primary' %>
    </p>
    <p class="control">
      <%= link_to 'Cancel', movies_path, :class => "button is-light" %>
    </p>
  </div>
<% end %>

app/views/movies/edit.html.erb
<div class="columns is-mobile is-centered">
  <div class="column is-half">
    <%= render 'form', movie: @movie %>
  </div>
</div>

app/views/movies/index.html.erb
<% if notice %>
  <div class="columns is-mobile is-centered">
    <div class="column is-half">
      <p id="notice" class="notification is-success"><%= notice %></p>
    </div>
  </div>
<% end %>

<div class="columns is-mobile is-centered">
  <div class="column is-half">
    <%= link_to 'Add a new movie', new_movie_path, :class => "button is-medium is-fullwidth is-primary" %>
  </div>
</div>

<div class="columns is-mobile is-centered">
  <div class="column is-half">
    <h3 class="title has-text-centered">Movies of page #<%= @random_page %></h3>
  </div>
</div>

<div class="columns is-mobile is-centered">
  <div class="column is-half">
    <p class="has-text-centered"><%= page_entries_info @movies, entry_name: 'movie' %></p>
  </div>
</div>

<%= paginate @movies %>
<br>


<div class="movies-table">
  <div class="table__wrapper">
    <table class="table is-bordered is-striped is-narrow is-hoverable is-fullwidth">
      <thead>
        <tr>
          <th>Title</th>
          <th>Description</th>
          <th>Movie length</th>
          <th>Release Date</th>
          <th>Rating</th>
          <th colspan="3">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @movies.each do |movie| %>
          <tr>
            <td><%= movie.title %></td>
            <td><%= sanitize(truncate(movie.description, length: 80)) %></td>
            <td><%= movie.movie_length %></td>
            <td><%= movie.release_date %></td>
            <td><%= movie.rating %></td>
            <td><%= link_to 'Show', movie, :class => "button is-light" %></td>
            <td><%= link_to 'Edit', edit_movie_path(movie), :class => "button is-info" %></td>
            <td><%= button_to "Destroy", movie_path(movie), method: :delete, :class => "button is-danger" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/movies/new.html.erb
<div class="columns is-mobile is-centered">
  <div class="column is-half">
    <%= render 'form', movie: @movie %>
  </div>
</div>

app/views/movies/show.html.erb
<div class="columns is-mobile is-centered">
  <div class="column is-half">
    <div class="card">
      <header class="card-header">
        <p class="card-header-title"><%= @movie.title.titleize %></p>
      </header>
      <div class="card-content">
        <div class="content">
          <%= @movie.description %>
        </div>
      </div>
      <footer class="tags card-footer is-centered" style="padding-top: 0.5em">
        <span class="tag is-rounded is-info is-large"><%= @movie.release_date %></span>
        <span class="tag is-rounded is-info is-large"><%= @movie.movie_length %></span>
        <span class="tag is-rounded is-info is-large"><%= @movie.rating %></span>
      </footer>
    </div>
  </div>
</div>
<div class="columns is-mobile is-centered">
  <div class="is-half" style="padding-top: 0.5em">
    <%= link_to 'All movies', movies_path, :class => "button is-light" %>
  </div>
</div>